name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build backend Docker container
      run: |
        cd backend
        docker-compose build

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 .

  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Lint frontend code
      run: |
        cd frontend
        npm install eslint
        npx eslint .
  
  docker-deploy:
    needs: [backend-build, frontend-build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend
      run: |
        cd backend
        docker-compose build
        docker-compose push

    - name: Build and push frontend
      run: |
        cd frontend
        docker-compose build
        docker-compose push
